version: "3"

services:
  nanomonitor:
    container_name: nanomonitor
    image: nanomonitor
    ports:
    - "80:80"
    networks:
      - backbone
    volumes:
      - ./docker/config.php:/var/www/html/modules/config.php
  nano:
    container_name: nano
    image: nanocurrency/nano
    networks:
      - backbone
    volumes:
      - ./docker:/root
    expose:
      - "7075"
      - "7076"
    ports:
            - "7076:7076"
networks:
  backbone:
    driver: bridge

